/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyAudio {
        "src": string;
    }
    interface MyClock {
        "delay": number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyHello {
    }
}
declare global {
    interface HTMLMyAudioElement extends Components.MyAudio, HTMLStencilElement {
    }
    var HTMLMyAudioElement: {
        prototype: HTMLMyAudioElement;
        new (): HTMLMyAudioElement;
    };
    interface HTMLMyClockElement extends Components.MyClock, HTMLStencilElement {
    }
    var HTMLMyClockElement: {
        prototype: HTMLMyClockElement;
        new (): HTMLMyClockElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyHelloElement extends Components.MyHello, HTMLStencilElement {
    }
    var HTMLMyHelloElement: {
        prototype: HTMLMyHelloElement;
        new (): HTMLMyHelloElement;
    };
    interface HTMLElementTagNameMap {
        "my-audio": HTMLMyAudioElement;
        "my-clock": HTMLMyClockElement;
        "my-component": HTMLMyComponentElement;
        "my-hello": HTMLMyHelloElement;
    }
}
declare namespace LocalJSX {
    interface MyAudio {
        "src"?: string;
    }
    interface MyClock {
        "delay"?: number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyHello {
    }
    interface IntrinsicElements {
        "my-audio": MyAudio;
        "my-clock": MyClock;
        "my-component": MyComponent;
        "my-hello": MyHello;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-audio": LocalJSX.MyAudio & JSXBase.HTMLAttributes<HTMLMyAudioElement>;
            "my-clock": LocalJSX.MyClock & JSXBase.HTMLAttributes<HTMLMyClockElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-hello": LocalJSX.MyHello & JSXBase.HTMLAttributes<HTMLMyHelloElement>;
        }
    }
}
